project:
  type: website

execute:
  freeze: auto

website:
  title: "notes"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "notebooks"
        menu: 
          - text: smolagent_test
            href: jupyter_notebooks/smolagent_test.ipynb
          - text: excel_agent
            href: jupyter_notebooks/excel_agent.ipynb
      - about.qmd
    tools:
          - icon: linkedin
            href: https://www.linkedin.com/in/haolei-hui-30b0bb29b/
          - icon: github
            href: https://github.com/haoleih

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
    #toc-location: left
    toc-title: Contents

