project:
  type: website

execute:
  freeze: auto

website:
  title: "Notes"
  sidebar:
    style: "docked"
    collapse-level: 3
    search: true
    contents:
      - text: "Introduction"
        href: index.qmd
      - section: "Notebooks"
        href: jupyter_notebooks/list.qmd
        contents:
          - text: Smolagent_test
            href: jupyter_notebooks/smolagent_test.ipynb
          - text: Excel_agent
            href: jupyter_notebooks/excel_agent.ipynb
          - text: Whisper automatic speech recognition
            href: jupyter_notebooks/whisper_ASR.ipynb
          - text: Phi-4 Multimodal Instruct Colab example
            href: jupyter_notebooks/Phi_4_multimodal.ipynb
      - about.qmd

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
    #toc-location: left
    toc-title: Contents
